import Image from "next/image"

const galleryArray= [
{
    src:"/assets/img/vyroba/1.png",
    alt:"navrh",
    text:"VŠECHNO ZAČÍNÁ POZOROVÁNÍM. V PŘÍRODĚ HLEDÁM TVAR, RYTMUS, PROPORCI I KLID — STRUKTURU POVRCHŮ, PŘIROZENÉ KŘIVKY, JEMNÉ NEPRAVIDELNOSTI I BAREVNOST, KTERÁ NEVZNIKÁ EFEKTEM, ALE ČASEM A MATERIÁLEM. Z TĚCHTO PODNĚTŮ VZNIKÁ PRVNÍ MYŠLENKA: K ČEMU BUDE VÝROBEK SLOUŽIT, JAK SE BUDE DRŽET V RUCE, JAK SE BUDE POUŽÍVAT A JAK BUDE PŮSOBIT V PROSTORU. NÁVRH PRO MĚ NENÍ JEN ESTETIKA. JE TO ROVNOVÁHA MEZI FUNKCÍ A CHARAKTEREM. ŘEŠÍM TLOUŠŤKU STĚN, STABILITU, ERGONOMII, OBJEM I DETAIL OKRAJE, KTERÝ ROZHODUJE O TOM, JAK SE Z VÝROBKU PIJE NEBO JAK SE S NÍM PRACUJE. TEPRVE KDYŽ JE FORMA I SMYSL JASNÝ, PŘICHÁZÍ ROZHODNUTÍ O POVRCHU, BARVĚ A PŘÍPADNÉM DEKORU."
},
{
    src:"/assets/img/vyroba/2.png",
    alt:"modelovani",
    text:"VŠECHNO ZAČÍNÁ POZOROVÁNÍM. V PŘÍRODĚ HLEDÁM TVAR, RYTMUS, PROPORCI I KLID — STRUKTURU POVRCHŮ, PŘIROZENÉ KŘIVKY, JEMNÉ NEPRAVIDELNOSTI I BAREVNOST, KTERÁ NEVZNIKÁ EFEKTEM, ALE ČASEM A MATERIÁLEM. Z TĚCHTO PODNĚTŮ VZNIKÁ PRVNÍ MYŠLENKA: K ČEMU BUDE VÝROBEK SLOUŽIT, JAK SE BUDE DRŽET V RUCE, JAK SE BUDE POUŽÍVAT A JAK BUDE PŮSOBIT V PROSTORU. NÁVRH PRO MĚ NENÍ JEN ESTETIKA. JE TO ROVNOVÁHA MEZI FUNKCÍ A CHARAKTEREM. ŘEŠÍM TLOUŠŤKU STĚN, STABILITU, ERGONOMII, OBJEM I DETAIL OKRAJE, KTERÝ ROZHODUJE O TOM, JAK SE Z VÝROBKU PIJE NEBO JAK SE S NÍM PRACUJE. TEPRVE KDYŽ JE FORMA I SMYSL JASNÝ, PŘICHÁZÍ ROZHODNUTÍ O POVRCHU, BARVĚ A PŘÍPADNÉM DEKORU."
},
{
    src:"/assets/img/vyroba/3.png",
    alt:"schnuti",
    text:"VŠECHNO ZAČÍNÁ POZOROVÁNÍM. V PŘÍRODĚ HLEDÁM TVAR, RYTMUS, PROPORCI I KLID — STRUKTURU POVRCHŮ, PŘIROZENÉ KŘIVKY, JEMNÉ NEPRAVIDELNOSTI I BAREVNOST, KTERÁ NEVZNIKÁ EFEKTEM, ALE ČASEM A MATERIÁLEM. Z TĚCHTO PODNĚTŮ VZNIKÁ PRVNÍ MYŠLENKA: K ČEMU BUDE VÝROBEK SLOUŽIT, JAK SE BUDE DRŽET V RUCE, JAK SE BUDE POUŽÍVAT A JAK BUDE PŮSOBIT V PROSTORU. NÁVRH PRO MĚ NENÍ JEN ESTETIKA. JE TO ROVNOVÁHA MEZI FUNKCÍ A CHARAKTEREM. ŘEŠÍM TLOUŠŤKU STĚN, STABILITU, ERGONOMII, OBJEM I DETAIL OKRAJE, KTERÝ ROZHODUJE O TOM, JAK SE Z VÝROBKU PIJE NEBO JAK SE S NÍM PRACUJE. TEPRVE KDYŽ JE FORMA I SMYSL JASNÝ, PŘICHÁZÍ ROZHODNUTÍ O POVRCHU, BARVĚ A PŘÍPADNÉM DEKORU."
},
{
    src:"/assets/img/vyroba/4.png",
    alt:"prezah",
    text:"VŠECHNO ZAČÍNÁ POZOROVÁNÍM. V PŘÍRODĚ HLEDÁM TVAR, RYTMUS, PROPORCI I KLID — STRUKTURU POVRCHŮ, PŘIROZENÉ KŘIVKY, JEMNÉ NEPRAVIDELNOSTI I BAREVNOST, KTERÁ NEVZNIKÁ EFEKTEM, ALE ČASEM A MATERIÁLEM. Z TĚCHTO PODNĚTŮ VZNIKÁ PRVNÍ MYŠLENKA: K ČEMU BUDE VÝROBEK SLOUŽIT, JAK SE BUDE DRŽET V RUCE, JAK SE BUDE POUŽÍVAT A JAK BUDE PŮSOBIT V PROSTORU. NÁVRH PRO MĚ NENÍ JEN ESTETIKA. JE TO ROVNOVÁHA MEZI FUNKCÍ A CHARAKTEREM. ŘEŠÍM TLOUŠŤKU STĚN, STABILITU, ERGONOMII, OBJEM I DETAIL OKRAJE, KTERÝ ROZHODUJE O TOM, JAK SE Z VÝROBKU PIJE NEBO JAK SE S NÍM PRACUJE. TEPRVE KDYŽ JE FORMA I SMYSL JASNÝ, PŘICHÁZÍ ROZHODNUTÍ O POVRCHU, BARVĚ A PŘÍPADNÉM DEKORU."
},
{
    src:"/assets/img/vyroba/5.png",
    alt:"glayurovvani",
    text:"VŠECHNO ZAČÍNÁ POZOROVÁNÍM. V PŘÍRODĚ HLEDÁM TVAR, RYTMUS, PROPORCI I KLID — STRUKTURU POVRCHŮ, PŘIROZENÉ KŘIVKY, JEMNÉ NEPRAVIDELNOSTI I BAREVNOST, KTERÁ NEVZNIKÁ EFEKTEM, ALE ČASEM A MATERIÁLEM. Z TĚCHTO PODNĚTŮ VZNIKÁ PRVNÍ MYŠLENKA: K ČEMU BUDE VÝROBEK SLOUŽIT, JAK SE BUDE DRŽET V RUCE, JAK SE BUDE POUŽÍVAT A JAK BUDE PŮSOBIT V PROSTORU. NÁVRH PRO MĚ NENÍ JEN ESTETIKA. JE TO ROVNOVÁHA MEZI FUNKCÍ A CHARAKTEREM. ŘEŠÍM TLOUŠŤKU STĚN, STABILITU, ERGONOMII, OBJEM I DETAIL OKRAJE, KTERÝ ROZHODUJE O TOM, JAK SE Z VÝROBKU PIJE NEBO JAK SE S NÍM PRACUJE. TEPRVE KDYŽ JE FORMA I SMYSL JASNÝ, PŘICHÁZÍ ROZHODNUTÍ O POVRCHU, BARVĚ A PŘÍPADNÉM DEKORU."
},
{
    src:"/assets/img/vyroba/6.png",
    alt:"vypal",
    text:"VŠECHNO ZAČÍNÁ POZOROVÁNÍM. V PŘÍRODĚ HLEDÁM TVAR, RYTMUS, PROPORCI I KLID — STRUKTURU POVRCHŮ, PŘIROZENÉ KŘIVKY, JEMNÉ NEPRAVIDELNOSTI I BAREVNOST, KTERÁ NEVZNIKÁ EFEKTEM, ALE ČASEM A MATERIÁLEM. Z TĚCHTO PODNĚTŮ VZNIKÁ PRVNÍ MYŠLENKA: K ČEMU BUDE VÝROBEK SLOUŽIT, JAK SE BUDE DRŽET V RUCE, JAK SE BUDE POUŽÍVAT A JAK BUDE PŮSOBIT V PROSTORU. NÁVRH PRO MĚ NENÍ JEN ESTETIKA. JE TO ROVNOVÁHA MEZI FUNKCÍ A CHARAKTEREM. ŘEŠÍM TLOUŠŤKU STĚN, STABILITU, ERGONOMII, OBJEM I DETAIL OKRAJE, KTERÝ ROZHODUJE O TOM, JAK SE Z VÝROBKU PIJE NEBO JAK SE S NÍM PRACUJE. TEPRVE KDYŽ JE FORMA I SMYSL JASNÝ, PŘICHÁZÍ ROZHODNUTÍ O POVRCHU, BARVĚ A PŘÍPADNÉM DEKORU."
},
{
    src:"/assets/img/vyroba/6.png",
    alt:"expedice",
    text:"VŠECHNO ZAČÍNÁ POZOROVÁNÍM. V PŘÍRODĚ HLEDÁM TVAR, RYTMUS, PROPORCI I KLID — STRUKTURU POVRCHŮ, PŘIROZENÉ KŘIVKY, JEMNÉ NEPRAVIDELNOSTI I BAREVNOST, KTERÁ NEVZNIKÁ EFEKTEM, ALE ČASEM A MATERIÁLEM. Z TĚCHTO PODNĚTŮ VZNIKÁ PRVNÍ MYŠLENKA: K ČEMU BUDE VÝROBEK SLOUŽIT, JAK SE BUDE DRŽET V RUCE, JAK SE BUDE POUŽÍVAT A JAK BUDE PŮSOBIT V PROSTORU. NÁVRH PRO MĚ NENÍ JEN ESTETIKA. JE TO ROVNOVÁHA MEZI FUNKCÍ A CHARAKTEREM. ŘEŠÍM TLOUŠŤKU STĚN, STABILITU, ERGONOMII, OBJEM I DETAIL OKRAJE, KTERÝ ROZHODUJE O TOM, JAK SE Z VÝROBKU PIJE NEBO JAK SE S NÍM PRACUJE. TEPRVE KDYŽ JE FORMA I SMYSL JASNÝ, PŘICHÁZÍ ROZHODNUTÍ O POVRCHU, BARVĚ A PŘÍPADNÉM DEKORU."
},

]

const Gallery = () => {

    return (
        <section className="Gallery">
        {galleryArray.map((item,index) => {
            const {src, alt, text} = item
            return (
                <div className="proces">
                       <p> {text}
                       </p>,
                    <div className="imggallery">
                       <Image src={src} alt={alt} fill />
                    </div>
                </div>

            )
        })}


        </section>
    )
}
export default Gallery